### ISSUE TITLE
ImportError: cannot import name 'iou3d_nms_cuda' from 'ops.iou3d_nms' (unknown location)

### ISSUE THREAD

**Issue by jyothsna-phd22** [shangjie-li/pointpillars#1]
(base) ouster@DESKTOP-5NO99NK:/mnt/c/users/student/my_jupyter/pointpillars$ python train.py --batch_size=2
Traceback (most recent call last):
  File "/mnt/c/users/student/my_jupyter/pointpillars/train.py", line 11, in <module>
    from data import cfg, cfg_from_list, cfg_from_yaml_file, log_config_to_file
  File "/mnt/c/users/student/my_jupyter/pointpillars/data/__init__.py", line 9, in <module>
    from .kitti_dataset import KittiDataset
  File "/mnt/c/users/student/my_jupyter/pointpillars/data/kitti_dataset.py", line 10, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/mnt/c/users/student/my_jupyter/pointpillars/data/augmentor/data_augmentor.py", line 3, in <module>
    from . import database_sampler
  File "/mnt/c/users/student/my_jupyter/pointpillars/data/augmentor/database_sampler.py", line 9, in <module>
    from ops.iou3d_nms import iou3d_nms_utils
  File "/mnt/c/users/student/my_jupyter/pointpillars/ops/iou3d_nms/iou3d_nms_utils.py", line 8, in <module>
    from . import iou3d_nms_cuda
ImportError: cannot import name 'iou3d_nms_cuda' from 'ops.iou3d_nms' (unknown location)

How to resolve this issue?

**Comment by shangjie-li** [comment]
Did you compile this project with "python setup.py develop"? After compilation, there will be "iou3d_nms_cuda" in pointpillars/ops/iou3d_nms.
